"""
OncoCare AI — Production Backend Server v2.0
============================================
Handles: File uploads, AI analysis, offline mode,
         treatment research, genetic analysis, chat,
         health checks, static file serving.

MEDICAL DISCLAIMER: All AI output is for research/education only.
Not a diagnosis. Always consult a qualified oncologist.
"""

import os
import sys
import json
import time
import uuid
import base64
import hashlib
import logging
import argparse
import datetime
import threading
import subprocess
from pathlib import Path

# ── Graceful imports ────────────────────────────────────────────
try:
    from flask import Flask, request, jsonify, send_from_directory, send_file
    from flask_cors import CORS
    FLASK_OK = True
except ImportError:
    print("[FATAL] Flask not installed. Run REPAIR_AND_RECOVER.bat")
    sys.exit(1)

try:
    import requests as req_lib
    REQUESTS_OK = True
except ImportError:
    REQUESTS_OK = False

try:
    from PIL import Image
    PIL_OK = True
except ImportError:
    PIL_OK = False

try:
    import fitz  # PyMuPDF
    FITZ_OK = True
except ImportError:
    FITZ_OK = False

try:
    import anthropic
    ANTHROPIC_OK = True
except ImportError:
    ANTHROPIC_OK = False

# ── Load knowledge engine ────────────────────────────────────────
try:
    sys.path.insert(0, str(BASE_DIR / "modules"))
    from knowledge_engine import build_rich_offline_report, get_cancer_list, find_cancer
    KNOWLEDGE_ENGINE = True
    log_init = True
except Exception as _ke:
    KNOWLEDGE_ENGINE = False
    log_init = False
    def build_rich_offline_report(cancer_type, stage, patient_info, section="all"):
        return build_offline_response(cancer_type, stage, patient_info, section)
    def get_cancer_list():
        return []

# ── Configuration ────────────────────────────────────────────────
BASE_DIR    = Path(__file__).parent.resolve()
UPLOAD_DIR  = BASE_DIR / "uploads"
LOGS_DIR    = BASE_DIR / "logs"
DATA_DIR    = BASE_DIR / "data"
STATIC_DIR  = BASE_DIR / "static"
REPORTS_DIR = BASE_DIR / "reports_db"
OFFLINE_DB  = DATA_DIR / "offline_knowledge.json"
SESSIONS_DB = DATA_DIR / "sessions.json"
CHAT_DB     = DATA_DIR / "chat_history.json"

for d in [UPLOAD_DIR, LOGS_DIR, DATA_DIR, STATIC_DIR, REPORTS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

PORT = int(os.environ.get("ONCOCARE_PORT", 5050))
API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
VERSION = "2.0.0"

# ── Logging ──────────────────────────────────────────────────────
log_file = LOGS_DIR / f"server_{datetime.date.today()}.log"
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s %(message)s",
    handlers=[
        logging.FileHandler(log_file, encoding="utf-8"),
        logging.StreamHandler(sys.stdout)
    ]
)
log = logging.getLogger("OncoCareAI")

# ── Flask App ────────────────────────────────────────────────────
app = Flask(__name__, static_folder=str(STATIC_DIR))
app.config["MAX_CONTENT_LENGTH"] = 200 * 1024 * 1024  # 200 MB
CORS(app, origins="*")

DISCLAIMER = (
    "⚠️ AI RESEARCH DISCLAIMER: All output is generated by AI from multiple "
    "internet and medical sources. Accuracy is not guaranteed. This is NOT a "
    "medical diagnosis or prescription. ALWAYS consult a qualified oncologist "
    "or medical specialist before any health decision. For research/education ONLY."
)

# ── Offline Knowledge Base ───────────────────────────────────────
OFFLINE_KNOWLEDGE = {
    "breast_cancer": {
        "overview": "Breast cancer arises from breast tissue. Most common cancer in women worldwide. Types include ductal carcinoma in situ (DCIS), invasive ductal carcinoma (IDC), invasive lobular carcinoma (ILC), inflammatory breast cancer, and triple-negative breast cancer.",
        "biomarkers": ["ER (Estrogen Receptor)", "PR (Progesterone Receptor)", "HER2/neu", "Ki-67", "BRCA1/BRCA2 mutations", "PIK3CA mutation", "PD-L1"],
        "staging": {"I": "Tumour ≤2cm, lymph node negative", "II": "Tumour 2–5cm or 1–3 lymph nodes", "III": "Locally advanced, >3 nodes or skin/chest wall", "IV": "Metastatic — liver, bone, lung, brain"},
        "allopathy": ["Surgery (lumpectomy/mastectomy)", "Chemotherapy: AC-T, TC, CMF, capecitabine", "Hormone therapy: Tamoxifen, Letrozole, Anastrozole, Fulvestrant", "Targeted: Trastuzumab (HER2+), Pertuzumab, Palbociclib, Ribociclib", "Immunotherapy: Pembrolizumab (TNBC)", "Radiation therapy"],
        "ayurveda": ["Ashwagandha — adaptogen, may support immune function", "Turmeric/Curcumin — anti-inflammatory, studied in breast cancer cell lines", "Tulsi — antioxidant, immunomodulatory", "Shatavari — hormonal support (check ER status with oncologist)", "Triphala — detoxification, antioxidant", "Guduchi — immune modulation"],
        "homeopathy": ["Conium maculatum — glandular tumours", "Phytolacca — breast lumps, tenderness", "Carcinosin — constitutional remedy", "Graphites — hard masses, skin involvement"],
        "diet": ["Anti-inflammatory: Broccoli, cauliflower, kale, berries", "Phytoestrogens (discuss ER+ status with oncologist): Flaxseed, soy", "Avoid: Alcohol, processed meat, high-fat dairy, sugar", "Prioritise: Omega-3 fatty acids, Mediterranean diet"],
        "yoga": ["Supported fish pose", "Gentle chest openers", "Pranayama: Anulom Vilom", "Yoga Nidra for sleep", "Walking 30 min/day"],
        "genetic_targets": ["BRCA1 17q21 — PARP inhibitors (olaparib, rucaparib)", "BRCA2 13q12 — Platinum chemotherapy sensitivity", "HER2 amplification — trastuzumab, lapatinib", "PIK3CA — alpelisib (Piqray)", "ESR1 mutation — elacestrant"],
        "clinical_trials_search": "https://clinicaltrials.gov/search?cond=Breast+Cancer"
    },
    "lung_cancer": {
        "overview": "Lung cancer: NSCLC (80%: adenocarcinoma, squamous cell, large cell) and SCLC (20%). Leading cause of cancer death globally. Strongly associated with smoking but also affects non-smokers (EGFR, ALK mutations common in non-smokers).",
        "biomarkers": ["EGFR mutation", "ALK rearrangement", "ROS1 rearrangement", "KRAS G12C", "BRAF V600E", "MET exon 14 skipping", "PD-L1 TPS", "TMB (Tumour Mutational Burden)"],
        "staging": {"I": "Localised to lung, no nodes", "II": "Hilar lymph nodes involved", "III": "Mediastinal nodes or chest wall", "IV": "Distant metastases — brain, bone, liver, adrenal"},
        "allopathy": ["Surgery: Lobectomy, segmentectomy, pneumonectomy", "Chemotherapy: Carboplatin/Paclitaxel, Cisplatin/Pemetrexed (adenocarcinoma)", "Targeted: Erlotinib/Osimertinib (EGFR), Alectinib/Brigatinib (ALK), Sotorasib (KRAS G12C)", "Immunotherapy: Pembrolizumab, Nivolumab, Atezolizumab, Durvalumab", "Radiation: SBRT (stereotactic body radiation therapy)", "Chemoradiation for Stage III"],
        "ayurveda": ["Tulsi — respiratory support, antioxidant", "Vasaka (Adhatoda vasica) — traditional bronchial remedy", "Pippali (long pepper) — lung tonic in Ayurvedic tradition", "Licorice root — respiratory, anti-inflammatory", "Ashwagandha — immune support, fatigue reduction"],
        "homeopathy": ["Arsenicum album — anxiety, weakness, respiratory", "Phosphorus — bleeding, respiratory affinity", "Stannum metallicum — respiratory exhaustion"],
        "diet": ["High antioxidant: Berries, green tea, cruciferous vegetables", "Ginger — anti-nausea support during chemotherapy", "Avoid: Smoking, alcohol, processed foods", "High protein to prevent muscle wasting: Lentils, eggs, fish"],
        "yoga": ["Pranpranayama: Bhramari, Anulom Vilom (improves lung capacity)", "Pursed lip breathing", "Gentle walking", "Avoid inverted poses if brain metastases"],
        "genetic_targets": ["EGFR — osimertinib (3rd gen), erlotinib/gefitinib", "ALK — alectinib, brigatinib, lorlatinib", "ROS1 — crizotinib, entrectinib", "KRAS G12C — sotorasib, adagrasib", "MET — capmatinib, tepotinib", "RET — selpercatinib"],
        "clinical_trials_search": "https://clinicaltrials.gov/search?cond=Lung+Cancer"
    },
    "colorectal_cancer": {
        "overview": "Colorectal cancer (CRC) affects the colon and rectum. Third most common cancer globally. Lynch syndrome (hereditary) accounts for ~3%. Sporadic CRC driven by APC, KRAS, TP53, SMAD4 mutations.",
        "biomarkers": ["KRAS/NRAS mutation (RAS status)", "BRAF V600E", "MSI-H/dMMR (mismatch repair)", "HER2 amplification", "CEA (Carcinoembryonic antigen)", "CA 19-9"],
        "staging": {"I": "Submucosa/muscularis propria", "II": "Through bowel wall, no nodes", "III": "Lymph node involvement", "IV": "Liver, lung, peritoneal metastases"},
        "allopathy": ["Surgery: Colectomy, hemicolectomy, TME (rectal)", "Chemotherapy: FOLFOX, FOLFIRI, CAPOX, capecitabine", "Targeted: Bevacizumab (anti-VEGF), Cetuximab/Panitumumab (RAS wild-type)", "Immunotherapy: Pembrolizumab, Nivolumab (MSI-H/dMMR)", "BRAF-targeted: Encorafenib + cetuximab (BRAF V600E)", "HIPEC for peritoneal disease"],
        "ayurveda": ["Triphala — bowel health, antioxidant, studied in colon cancer lines", "Turmeric — anti-inflammatory, NF-kB inhibition", "Kutaja (Holarrhena antidysenterica) — bowel support", "Guduchi — immune support"],
        "diet": ["High fibre: Whole grains, legumes, vegetables", "Probiotics: Yoghurt, kefir, kimchi", "Avoid: Processed/red meat, alcohol, low-fibre diet", "Cruciferous vegetables, garlic, onion"],
        "genetic_targets": ["MSI-H/dMMR — pembrolizumab (first-line approved)", "BRAF V600E — encorafenib + cetuximab", "HER2 — trastuzumab + pertuzumab (2L+)", "NTRK — larotrectinib, entrectinib"],
        "clinical_trials_search": "https://clinicaltrials.gov/search?cond=Colorectal+Cancer"
    },
    "leukemia": {
        "overview": "Blood cancer: AML (acute myeloid), ALL (acute lymphoblastic), CML (chronic myeloid), CLL (chronic lymphocytic). Affects bone marrow and blood. Treatment highly type-specific.",
        "biomarkers": ["BCR-ABL (Philadelphia chromosome — CML/ALL)", "FLT3 mutation (AML)", "NPM1 mutation (AML)", "IDH1/IDH2 (AML)", "TP53", "Karyotype/cytogenetics"],
        "allopathy": ["AML: 7+3 induction (cytarabine+daunorubicin), venetoclax+azacitidine (elderly)", "CML: Imatinib, dasatinib, nilotinib, ponatinib (TKIs)", "ALL: Hyper-CVAD, blinatumomab, inotuzumab", "CLL: Ibrutinib, acalabrutinib, venetoclax+obinutuzumab", "Stem cell transplant (allogeneic BMT) for high-risk", "CAR-T: Tisagenlecleucel (ALL), brexucabtagene (MCL)"],
        "genetic_targets": ["BCR-ABL — imatinib/dasatinib/nilotinib", "FLT3-ITD — midostaurin, gilteritinib", "IDH1 — ivosidenib", "IDH2 — enasidenib", "BTK (CLL) — ibrutinib, zanubrutinib"],
        "clinical_trials_search": "https://clinicaltrials.gov/search?cond=Leukemia"
    },
    "prostate_cancer": {
        "overview": "Most common male cancer. Usually slow-growing. Graded by Gleason score. PSA screening controversial but widely used. Hormone-sensitive vs castration-resistant are key treatment distinctions.",
        "biomarkers": ["PSA (Prostate-Specific Antigen)", "Gleason score / Grade Group", "PSMA (PET imaging)", "AR splice variant 7 (ARV7)", "BRCA2", "ATM mutation", "MSI-H"],
        "allopathy": ["Active surveillance (low risk)", "Surgery: Radical prostatectomy (robotic-assisted)", "Radiation: EBRT, brachytherapy, SBRT", "Hormone therapy (ADT): LHRH agonists/antagonists, abiraterone, enzalutamide, darolutamide", "Chemotherapy: Docetaxel, cabazitaxel", "PSMA-targeted: 177Lu-PSMA-617 (Pluvicto)", "PARP inhibitors: Olaparib (BRCA+)"],
        "genetic_targets": ["BRCA1/2 — olaparib, rucaparib", "ATM — olaparib", "MSI-H — pembrolizumab", "PSMA expression — lutetium-177 PSMA"],
        "clinical_trials_search": "https://clinicaltrials.gov/search?cond=Prostate+Cancer"
    },
    "general": {
        "personalised_medicine": "Personalised cancer medicine uses an individual's genomic profile to match them to optimal treatments. This includes: Next-Generation Sequencing (NGS) of tumour tissue, liquid biopsy (ctDNA), germline genetic testing (BRCA etc.), and matching to targeted therapies or clinical trials. Pioneered by institutions like MD Anderson, Mayo Clinic, Sloan Kettering, and Tata Memorial in India.",
        "custom_vaccines": "Personalised cancer vaccines (neoantigen vaccines) identify tumour-specific mutations unique to each patient's cancer and train the immune system to attack those cells. Example: Sid Sijbrandij (GitLab CEO) received 19 custom neoantigen vaccines derived from his own tumour DNA, achieving cancer-free status by 2025. This is being developed by BioNTech, Moderna (mRNA-4157), NeoVax, and Gritstone Bio.",
        "car_t": "CAR-T (Chimeric Antigen Receptor T-cell) therapy engineers a patient's own T-cells to recognise and kill cancer. Approved products: Kymriah (ALL, DLBCL), Yescarta (DLBCL), Carvykti (myeloma), Breyanzi. Research expanding to solid tumours.",
        "india_resources": {
            "hospitals": ["Tata Memorial Hospital, Mumbai — tmc.gov.in", "AIIMS, New Delhi — aiims.edu", "Rajiv Gandhi Cancer Institute, Delhi — rgcirc.org", "Kidwai Memorial, Bengaluru", "Apollo Hospitals — apollohospitals.com", "Medanta, Gurugram — medanta.org"],
            "helplines": ["iCall: 9152987821", "Vandrevala Foundation: 1860-2662-345", "CPAA: cpaa.org.in", "Can Support India: cansupport.in", "National Cancer Grid: ncg.tmc.gov.in"],
            "clinical_trials": "https://ctri.nic.in"
        }
    }
}

def save_offline_knowledge():
    with open(OFFLINE_DB, "w", encoding="utf-8") as f:
        json.dump(OFFLINE_KNOWLEDGE, f, indent=2)

def load_sessions():
    if SESSIONS_DB.exists():
        with open(SESSIONS_DB, "r") as f:
            return json.load(f)
    return {}

def save_session(session_id, data):
    sessions = load_sessions()
    sessions[session_id] = {**data, "updated": datetime.datetime.now().isoformat()}
    with open(SESSIONS_DB, "w") as f:
        json.dump(sessions, f, indent=2)

def load_chat():
    if CHAT_DB.exists():
        with open(CHAT_DB, "r") as f:
            return json.load(f)
    return {"messages": [], "doctors": []}

def save_chat(msg):
    chat = load_chat()
    chat["messages"].append({**msg, "id": str(uuid.uuid4()), "timestamp": datetime.datetime.now().isoformat()})
    chat["messages"] = chat["messages"][-500:]  # Keep last 500
    with open(CHAT_DB, "w") as f:
        json.dump(chat, f, indent=2)

def extract_pdf_text(filepath):
    if not FITZ_OK:
        return "[PDF extraction unavailable — PyMuPDF not installed]"
    try:
        doc = fitz.open(str(filepath))
        text = ""
        for page in doc:
            text += page.get_text()
        doc.close()
        return text[:8000]  # Limit for API context
    except Exception as e:
        return f"[PDF extraction error: {e}]"

def extract_image_info(filepath):
    if not PIL_OK:
        return "[Image analysis unavailable — Pillow not installed]"
    try:
        img = Image.open(str(filepath))
        return f"Image: {img.format}, {img.size[0]}x{img.size[1]}px, Mode: {img.mode}"
    except Exception as e:
        return f"[Image error: {e}]"

def is_online():
    try:
        if REQUESTS_OK:
            req_lib.get("https://8.8.8.8", timeout=3)
            return True
    except:
        pass
    return False

def call_claude_api(prompt, system_prompt=None, max_tokens=2000):
    """Call Claude API with fallback to offline mode."""
    if not API_KEY:
        return None, "no_api_key"

    if not REQUESTS_OK:
        return None, "requests_not_installed"

    if not is_online():
        return None, "offline"

    if not system_prompt:
        system_prompt = (
            "You are OncoCare AI, a medical research assistant helping cancer patients understand their condition. "
            "You ALWAYS: 1) Start with a brief disclaimer that this is AI-generated research. "
            "2) Provide well-structured, compassionate, thorough information. "
            "3) Cover allopathic, ayurvedic, and holistic perspectives where relevant. "
            "4) End with a reminder to consult a qualified oncologist. "
            "You research across oncology literature, clinical trial databases, and traditional medicine. "
            "Be specific, evidence-informed, and compassionate. Never refuse to provide research information."
        )

    try:
        response = req_lib.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json"
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": max_tokens,
                "system": system_prompt,
                "messages": [{"role": "user", "content": prompt}]
            },
            timeout=90
        )
        if response.status_code == 200:
            data = response.json()
            return data["content"][0]["text"], "live_ai"
        else:
            log.error(f"Claude API error {response.status_code}: {response.text[:200]}")
            return None, f"api_error_{response.status_code}"
    except Exception as e:
        log.error(f"Claude API exception: {e}")
        return None, str(e)

def build_offline_response(cancer_type, stage, patient_info, analysis_type):
    """Build a rich offline research response from embedded knowledge."""
    ct = cancer_type.lower().replace(" ", "_").replace("-", "_")
    # Find best matching key
    match = "general"
    for key in OFFLINE_KNOWLEDGE:
        if key in ct or ct in key:
            match = key
            break

    kb = OFFLINE_KNOWLEDGE.get(match, OFFLINE_KNOWLEDGE["general"])
    gen = OFFLINE_KNOWLEDGE["general"]

    if match == "general":
        type_info = f"**{cancer_type}** research is available through our offline knowledge base."
    else:
        type_info = kb.get("overview", f"Research data for {cancer_type}.")

    lines = [
        f"## OncoCare AI Research Report — Offline Mode",
        f"**Cancer Type:** {cancer_type}  |  **Stage:** {stage}",
        f"**Mode:** Offline Research (Embedded Medical Knowledge Base)",
        f"",
        f"---",
        f"",
        f"### Overview",
        type_info,
        f"",
    ]

    if "staging" in kb:
        lines += [f"### Staging Reference (TNM/AJCC)"]
        for s, desc in kb["staging"].items():
            lines.append(f"- **Stage {s}:** {desc}")
        lines.append("")

    if "biomarkers" in kb:
        lines += [f"### Key Biomarkers & Molecular Targets"]
        for bm in kb["biomarkers"]:
            lines.append(f"- {bm}")
        lines.append("")

    if "allopathy" in kb and analysis_type in ["all", "allopathy", "diagnostic"]:
        lines += [f"### Allopathic Treatment Options (Researched)"]
        for t in kb["allopathy"]:
            lines.append(f"- {t}")
        lines.append("")

    if "ayurveda" in kb and analysis_type in ["all", "ayurveda"]:
        lines += [f"### Ayurvedic Research (Complementary Only)"]
        for a in kb["ayurveda"]:
            lines.append(f"- {a}")
        lines.append("")

    if "homeopathy" in kb and analysis_type in ["all", "homeopathy"]:
        lines += [f"### Homeopathic Literature (Research Only)"]
        for h in kb["homeopathy"]:
            lines.append(f"- {h}")
        lines.append("")

    if "genetic_targets" in kb and analysis_type in ["all", "genetic"]:
        lines += [f"### Genetic/Molecular Targets & Matched Therapies"]
        for g in kb["genetic_targets"]:
            lines.append(f"- {g}")
        lines.append("")
        lines += [
            f"### Personalised Medicine Research",
            gen["personalised_medicine"],
            f"",
            f"### Personalised Cancer Vaccines",
            gen["custom_vaccines"],
            f"",
            f"### CAR-T Cell Therapy",
            gen["car_t"],
            f""
        ]

    if "diet" in kb and analysis_type in ["all", "lifestyle"]:
        lines += [f"### Dietary Research for {cancer_type}"]
        for d in kb["diet"]:
            lines.append(f"- {d}")
        lines.append("")

    if "yoga" in kb and analysis_type in ["all", "yoga"]:
        lines += [f"### Yoga & Movement Therapy"]
        for y in kb["yoga"]:
            lines.append(f"- {y}")
        lines.append("")

    if "clinical_trials_search" in kb:
        lines += [
            f"### Clinical Trials",
            f"Search open trials: [{kb['clinical_trials_search']}]({kb['clinical_trials_search']})",
            f"India trials: https://ctri.nic.in",
            f""
        ]

    lines += [
        f"---",
        f"",
        f"### India Cancer Resources",
    ]
    for h in gen["india_resources"]["hospitals"]:
        lines.append(f"- {h}")
    lines += [
        f"",
        f"**Helplines:** " + " | ".join(gen["india_resources"]["helplines"]),
        f"",
        f"---",
        f"",
        f"⚠️ **{DISCLAIMER}**"
    ]

    return "\n".join(lines)

# ══════════════════════════════════════════════════════════════════
# ROUTES
# ══════════════════════════════════════════════════════════════════

@app.route("/")
def index():
    return send_from_directory(str(STATIC_DIR), "index.html")

@app.route("/<path:filename>")
def static_files(filename):
    return send_from_directory(str(STATIC_DIR), filename)

@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({
        "status": "ok",
        "version": VERSION,
        "online": is_online(),
        "api_key_set": bool(API_KEY),
        "live_ai": bool(API_KEY) and is_online(),
        "pil": PIL_OK,
        "pdf": FITZ_OK,
        "anthropic_sdk": ANTHROPIC_OK,
        "timestamp": datetime.datetime.now().isoformat()
    })

@app.route("/api/upload", methods=["POST"])
def upload():
    if "files" not in request.files:
        return jsonify({"error": "No files in request"}), 400

    results = []
    session_id = request.form.get("session_id") or str(uuid.uuid4())
    session_dir = UPLOAD_DIR / session_id
    session_dir.mkdir(parents=True, exist_ok=True)

    for f in request.files.getlist("files"):
        if not f.filename:
            continue
        ext = Path(f.filename).suffix.lower()
        safe_name = f"{uuid.uuid4().hex}{ext}"
        dest = session_dir / safe_name
        f.save(str(dest))
        size = dest.stat().st_size

        # Extract content for analysis
        extracted = ""
        file_type = "unknown"
        if ext == ".pdf":
            extracted = extract_pdf_text(dest)
            file_type = "pdf"
        elif ext in [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".dcm"]:
            extracted = extract_image_info(dest)
            file_type = "image"
        elif ext in [".txt", ".csv"]:
            try:
                extracted = dest.read_text(encoding="utf-8", errors="ignore")[:5000]
            except:
                extracted = ""
            file_type = "text"

        results.append({
            "original_name": f.filename,
            "saved_as": safe_name,
            "size_bytes": size,
            "size_kb": round(size / 1024, 1),
            "type": file_type,
            "extension": ext,
            "extracted_preview": extracted[:300] if extracted else "",
            "has_content": bool(extracted)
        })
        log.info(f"Uploaded: {f.filename} → {safe_name} ({size} bytes)")

    # Save session
    existing = load_sessions().get(session_id, {})
    existing_files = existing.get("files", [])
    existing_files.extend(results)
    save_session(session_id, {
        "session_id": session_id,
        "files": existing_files,
        "created": existing.get("created", datetime.datetime.now().isoformat())
    })

    return jsonify({
        "success": True,
        "session_id": session_id,
        "uploaded": len(results),
        "files": results,
        "disclaimer": DISCLAIMER
    })

@app.route("/api/analyse", methods=["POST"])
def analyse():
    data = request.json or {}
    cancer_type  = data.get("cancer_type", "Unknown Cancer")
    stage        = data.get("stage", "Unknown Stage")
    patient_info = data.get("patient_info", {})
    analysis_type = data.get("analysis_type", "all")
    session_id   = data.get("session_id", "")

    log.info(f"Analysis request: {cancer_type} | {stage} | type={analysis_type}")

    # Build context from uploaded files
    file_context = ""
    if session_id:
        sessions = load_sessions()
        if session_id in sessions:
            files = sessions[session_id].get("files", [])
            file_context = f"\n\nUploaded Reports ({len(files)} files):\n"
            for fi in files[:10]:
                file_context += f"- {fi['original_name']} ({fi['type']}, {fi['size_kb']} KB)\n"
                if fi.get("extracted_preview"):
                    file_context += f"  Preview: {fi['extracted_preview'][:200]}...\n"

    prompt = f"""
Patient Cancer Research Request:
Cancer Type: {cancer_type}
Stage: {stage}
Patient Age: {patient_info.get("age", "Not specified")}
Gender: {patient_info.get("gender", "Not specified")}
Current Treatment: {patient_info.get("current_treatment", "None specified")}
Other Conditions: {patient_info.get("conditions", "None specified")}
Symptoms: {patient_info.get("symptoms", "Not specified")}
Analysis Requested: {analysis_type}
{file_context}

Please provide comprehensive research covering:
1. Cancer overview and staging context for the indicated stage
2. Key biomarkers and what they mean for treatment decisions
3. Standard allopathic treatment protocols (most current guidelines)
4. Complementary approaches: Ayurvedic and homeopathic research
5. Nutritional and dietary recommendations specific to this cancer type and stage
6. Yoga/exercise protocols safe for this patient's situation
7. Genetic/personalised medicine opportunities (CAR-T, neoantigen vaccines, targeted therapy matching)
8. Psychological support frameworks
9. Questions this patient should ask their oncologist
10. Relevant clinical trials to explore (mention ClinicalTrials.gov and CTRI India)

Be thorough, compassionate, and specific. Use subheadings. Write in clear language a patient can understand.
"""

    result, mode = call_claude_api(prompt)

    if result is None:
        log.info(f"Using offline mode: {mode}")
        result = build_offline_response(cancer_type, stage, patient_info, analysis_type)
        mode = "offline"

    return jsonify({
        "success": True,
        "mode": mode,
        "analysis": result,
        "cancer_type": cancer_type,
        "stage": stage,
        "disclaimer": DISCLAIMER,
        "timestamp": datetime.datetime.now().isoformat()
    })

@app.route("/api/treatment/<ttype>", methods=["POST"])
def treatment(ttype):
    data = request.json or {}
    cancer_type = data.get("cancer_type", "the indicated cancer")
    stage = data.get("stage", "")

    valid = ["allopathy", "ayurveda", "homeopathy", "genetic", "lifestyle", "yoga", "psychology"]
    if ttype not in valid:
        return jsonify({"error": f"Unknown type. Must be one of: {valid}"}), 400

    prompt_map = {
        "allopathy": f"Provide a detailed evidence-based overview of allopathic/conventional oncology treatment options for {cancer_type} at {stage}. Include: current standard of care protocols, chemotherapy regimens, targeted therapies, immunotherapy options, surgical approaches, radiation techniques. Cite major guidelines (NCCN, ESMO, ASCO).",
        "ayurveda": f"Research and summarise Ayurvedic approaches studied or used as complementary therapy for {cancer_type}. Include specific herbs (with botanical names), classical formulations, Panchakarma relevance, evidence from research papers, and integration with conventional treatment. Note any contraindications with common cancer medications.",
        "homeopathy": f"Research homeopathic literature regarding {cancer_type}. Include constitutional remedies discussed in homeopathic cancer texts, supportive care remedies for treatment side effects, key remedies (potency, frequency) as described in literature. Be clear about the evidence level and that this is research-only.",
        "genetic": f"Provide comprehensive personalised medicine research for {cancer_type}. Include: relevant genetic mutations and their therapeutic implications, matched targeted therapies, PARP inhibitors, immunotherapy biomarkers (PD-L1, TMB, MSI), liquid biopsy, personalised neoantigen vaccine research, CAR-T eligibility, clinical trial matching approach, and how to get an NGS panel done in India.",
        "lifestyle": f"Design a comprehensive cancer-supportive lifestyle and nutrition plan for a patient with {cancer_type} at {stage}. Include: anti-cancer diet principles, specific foods to eat and avoid, sample meal plan, hydration, gut microbiome support, supplement research (with cautions), sleep hygiene, stress reduction.",
        "yoga": f"Design a safe, evidence-informed yoga and exercise programme for a {cancer_type} patient at {stage}. Include: specific asanas (with modifications), pranayama sequences, duration and frequency, contraindications, MBSR (mindfulness-based stress reduction) protocol, lymphatic support exercises.",
        "psychology": f"Provide a comprehensive psychological support framework for a {cancer_type} patient. Include: CBT techniques for cancer anxiety, ACT (Acceptance & Commitment Therapy) principles, fear of recurrence management, family/caregiver support strategies, body image issues, managing 'chemo brain', existential concerns, India-specific helplines and support groups."
    }

    result, mode = call_claude_api(prompt_map[ttype])
    if result is None:
        result = build_offline_response(cancer_type, stage, {}, ttype)
        mode = "offline"

    return jsonify({"success": True, "type": ttype, "mode": mode, "content": result, "disclaimer": DISCLAIMER})

@app.route("/api/genetic/analyse", methods=["POST"])
def genetic_analyse():
    data = request.json or {}
    cancer_type = data.get("cancer_type", "")
    genetic_text = data.get("genetic_text", "")

    prompt = f"""
Analyse this genetic/genomic report data for a patient with {cancer_type}:

{genetic_text[:3000] if genetic_text else "(No report text provided — provide general genetic analysis framework)"}

Research and provide:
1. Identification of any mentioned mutations and their clinical significance
2. Matched targeted therapies for each mutation (with drug names)
3. PARP inhibitor eligibility (BRCA1/2, ATM, PALB2)
4. Immunotherapy biomarkers (PD-L1, TMB, MSI-H/dMMR)
5. Personalised neoantigen vaccine suitability research
6. CAR-T eligibility based on cancer type and markers
7. Drug repurposing opportunities identified in recent literature
8. Top 5 clinical trials to consider based on molecular profile
9. Which specialised oncogenomics centres in India to consult (Tata Memorial, AIIMS, etc.)
10. What additional genetic tests to request from their oncologist

Format clearly with subheadings. Be specific with drug names and mutation-therapy pairs.
"""

    result, mode = call_claude_api(prompt, max_tokens=2500)
    if result is None:
        result = build_offline_response(cancer_type, "", {}, "genetic")
        mode = "offline"

    return jsonify({"success": True, "mode": mode, "analysis": result, "disclaimer": DISCLAIMER})

@app.route("/api/chat/send", methods=["POST"])
def chat_send():
    data = request.json or {}
    message = data.get("message", "").strip()
    sender  = data.get("sender", "Anonymous Patient")
    role    = data.get("role", "patient")

    if not message:
        return jsonify({"error": "Empty message"}), 400

    msg = {"sender": sender, "role": role, "message": message}
    save_chat(msg)

    # Get AI response if it's a direct question
    ai_response = None
    if data.get("request_ai_response", False) and is_online() and API_KEY:
        prompt = f"A cancer patient/community member asks: '{message}'\n\nProvide a compassionate, research-informed response. Keep it concise (3-4 paragraphs). Always remind them to consult their oncologist for medical decisions."
        ai_response, _ = call_claude_api(prompt, max_tokens=600)

    return jsonify({
        "success": True,
        "message_id": str(uuid.uuid4()),
        "disclaimer": "Messages here are not verified medical advice. Consult your oncology team.",
        "ai_response": ai_response
    })

@app.route("/api/chat/history", methods=["GET"])
def chat_history():
    chat = load_chat()
    return jsonify({"messages": chat["messages"][-100:], "total": len(chat["messages"])})

@app.route("/api/session/<session_id>", methods=["GET"])
def get_session(session_id):
    sessions = load_sessions()
    if session_id not in sessions:
        return jsonify({"error": "Session not found"}), 404
    return jsonify(sessions[session_id])

@app.route("/api/status", methods=["GET"])
def status():
    online = is_online()
    return jsonify({
        "server": "running",
        "version": VERSION,
        "online": online,
        "mode": "live_ai" if (online and API_KEY) else "offline_research",
        "api_key": "configured" if API_KEY else "not_set",
        "capabilities": {
            "pdf_extraction": FITZ_OK,
            "image_processing": PIL_OK,
            "live_ai": bool(API_KEY and online),
            "offline_research": True,
            "chat": True,
            "genetic_analysis": True
        },
        "uptime": "running",
        "disclaimer": DISCLAIMER
    })

@app.route("/api/knowledge/cancers", methods=["GET"])
def list_cancers():
    if KNOWLEDGE_ENGINE:
        cancer_list = get_cancer_list()
        return jsonify({"cancers": cancer_list, "total": len(cancer_list), "engine": "full"})
    return jsonify({"cancers": list(OFFLINE_KNOWLEDGE.keys()), "total": len(OFFLINE_KNOWLEDGE), "engine": "basic"})

@app.route("/api/report/generate", methods=["POST"])
def generate_report():
    data = request.json or {}
    session_id  = data.get("session_id", "")
    cancer_type = data.get("cancer_type", "Unknown")
    stage       = data.get("stage", "Unknown")
    patient_info = data.get("patient_info", {})

    # Build full report
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    report_id = f"report_{timestamp}_{uuid.uuid4().hex[:6]}"

    content = build_offline_response(cancer_type, stage, patient_info, "all")
    if API_KEY and is_online():
        ai_content, mode = call_claude_api(
            f"Generate a comprehensive cancer research report for: {cancer_type} Stage {stage}. Patient: {patient_info}. Include all treatment options, diet, yoga, genetics, psychology. Format as a detailed report.",
            max_tokens=3000
        )
        if ai_content:
            content = ai_content

    report = {
        "report_id": report_id,
        "generated": datetime.datetime.now().isoformat(),
        "cancer_type": cancer_type,
        "stage": stage,
        "patient_info": patient_info,
        "content": content,
        "disclaimer": DISCLAIMER
    }

    report_file = REPORTS_DIR / f"{report_id}.json"
    with open(report_file, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    log.info(f"Report generated: {report_id}")
    return jsonify(report)

# ── Static file generation (for --generate-static arg) ─────────
def generate_static_files():
    """Called when server.py --generate-static is passed — regenerates index.html"""
    log.info("Generating static files...")
    STATIC_DIR.mkdir(exist_ok=True)
    # The HTML is embedded below — write it out
    html_file = STATIC_DIR / "index.html"
    if not html_file.exists():
        log.warning("index.html not found in static/ — please ensure the ZIP was extracted completely.")

# ── Main ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="OncoCare AI Server")
    parser.add_argument("--port", type=int, default=PORT)
    parser.add_argument("--generate-static", action="store_true")
    parser.add_argument("--repair-only", action="store_true")
    args = parser.parse_args()

    if args.generate_static or args.repair_only:
        generate_static_files()
        sys.exit(0)

    # Save offline knowledge DB
    save_offline_knowledge()

    log.info("=" * 60)
    log.info(f"  OncoCare AI Server v{VERSION} Starting")
    log.info("=" * 60)
    log.info(f"  Port:        {args.port}")
    log.info(f"  Online:      {is_online()}")
    log.info(f"  Live AI:     {'YES' if (API_KEY and is_online()) else 'NO (offline/demo mode)'}")
    log.info(f"  PDF Extract: {FITZ_OK}")
    log.info(f"  Images:      {PIL_OK}")
    log.info(f"  Static dir:  {STATIC_DIR}")
    log.info(f"  Uploads:     {UPLOAD_DIR}")
    log.info(f"  Logs:        {LOGS_DIR}")
    log.info("=" * 60)
    log.info(f"  URL: http://localhost:{args.port}")
    log.info("=" * 60)
    log.info(DISCLAIMER)
    log.info("=" * 60)

    app.run(
        host="0.0.0.0",
        port=args.port,
        debug=False,
        threaded=True,
        use_reloader=False
    )
